<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Midrange | Math 115: Elementary Statistics</title>
  <meta name="description" content="These are the slides I use in class. Most of the materials are obtained from our textbook: Elementary Statistics 13th edition by Mario F. Triola." />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Midrange | Math 115: Elementary Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="These are the slides I use in class. Most of the materials are obtained from our textbook: Elementary Statistics 13th edition by Mario F. Triola." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Midrange | Math 115: Elementary Statistics" />
  
  <meta name="twitter:description" content="These are the slides I use in class. Most of the materials are obtained from our textbook: Elementary Statistics 13th edition by Mario F. Triola." />
  

<meta name="author" content="Rong You" />


<meta name="date" content="2019-08-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="descriptive-statistics.html">
<link rel="next" href="methods.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />










<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Chapter 1</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#welcome"><i class="fa fa-check"></i><b>1.1</b> Welcome</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#statistical-and-critical-thinking"><i class="fa fa-check"></i><b>1.2</b> Statistical and Critical Thinking</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#example-1"><i class="fa fa-check"></i><b>1.3</b> Example 1</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#example-2"><i class="fa fa-check"></i><b>1.4</b> Example 2</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#statistical-thinking-procedure"><i class="fa fa-check"></i><b>1.5</b> Statistical Thinking Procedure:</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#types-of-data"><i class="fa fa-check"></i><b>1.6</b> Types of Data</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#example-3"><i class="fa fa-check"></i><b>1.7</b> Example 3</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#levels-of-measurement"><i class="fa fa-check"></i><b>1.8</b> Levels of Measurement</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#summary---levels-of-measurement"><i class="fa fa-check"></i><b>1.9</b> Summary - Levels of Measurement</a></li>
<li class="chapter" data-level="1.10" data-path="index.html"><a href="index.html#big-data-and-data-science"><i class="fa fa-check"></i><b>1.10</b> Big Data and Data Science</a></li>
<li class="chapter" data-level="1.11" data-path="index.html"><a href="index.html#how-do-we-gather-data"><i class="fa fa-check"></i><b>1.11</b> How do we gather data?</a></li>
<li class="chapter" data-level="1.12" data-path="index.html"><a href="index.html#how-good-a-poll-would-be"><i class="fa fa-check"></i><b>1.12</b> How good a poll would be?</a></li>
<li class="chapter" data-level="1.13" data-path="index.html"><a href="index.html#basics-of-collecting-data"><i class="fa fa-check"></i><b>1.13</b> Basics of Collecting Data</a></li>
<li class="chapter" data-level="1.14" data-path="index.html"><a href="index.html#observational-study-survey"><i class="fa fa-check"></i><b>1.14</b> Observational Study: Survey</a></li>
<li class="chapter" data-level="1.15" data-path="index.html"><a href="index.html#sampling-methods"><i class="fa fa-check"></i><b>1.15</b> Sampling Methods:</a></li>
<li class="chapter" data-level="1.16" data-path="index.html"><a href="index.html#sampling-methods-simple-random-sample"><i class="fa fa-check"></i><b>1.16</b> Sampling Methods: Simple Random Sample</a></li>
<li class="chapter" data-level="1.17" data-path="index.html"><a href="index.html#samping-methods-systematic-sampling"><i class="fa fa-check"></i><b>1.17</b> Samping Methods: Systematic Sampling</a></li>
<li class="chapter" data-level="1.18" data-path="index.html"><a href="index.html#sampling-methods-stratified-random-sample"><i class="fa fa-check"></i><b>1.18</b> Sampling Methods: Stratified random sample</a></li>
<li class="chapter" data-level="1.19" data-path="index.html"><a href="index.html#sampling-methods-cluster-sampling"><i class="fa fa-check"></i><b>1.19</b> Sampling Methods: Cluster Sampling</a></li>
<li class="chapter" data-level="1.20" data-path="index.html"><a href="index.html#sampling-methods-convenience-sampling"><i class="fa fa-check"></i><b>1.20</b> Sampling Methods: Convenience sampling</a></li>
<li class="chapter" data-level="1.21" data-path="index.html"><a href="index.html#summary-of-sampling-methods"><i class="fa fa-check"></i><b>1.21</b> Summary of Sampling Methods</a></li>
<li class="chapter" data-level="1.22" data-path="index.html"><a href="index.html#example-4"><i class="fa fa-check"></i><b>1.22</b> Example 4</a></li>
<li class="chapter" data-level="1.23" data-path="index.html"><a href="index.html#bias"><i class="fa fa-check"></i><b>1.23</b> Bias</a></li>
<li class="chapter" data-level="1.24" data-path="index.html"><a href="index.html#potential-pitfalls"><i class="fa fa-check"></i><b>1.24</b> Potential Pitfalls</a></li>
<li class="chapter" data-level="1.25" data-path="index.html"><a href="index.html#experimental-design"><i class="fa fa-check"></i><b>1.25</b> Experimental Design</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="graphical-displas.html"><a href="graphical-displas.html"><i class="fa fa-check"></i><b>2</b> Graphical Displas</a><ul>
<li class="chapter" data-level="2.1" data-path="graphical-displas.html"><a href="graphical-displas.html#frequency-distribution"><i class="fa fa-check"></i><b>2.1</b> Frequency Distribution</a></li>
<li class="chapter" data-level="2.2" data-path="graphical-displas.html"><a href="graphical-displas.html#procedure-for-constructing-a-frequency-distribution"><i class="fa fa-check"></i><b>2.2</b> Procedure for Constructing a Frequency Distribution</a></li>
<li class="chapter" data-level="2.3" data-path="graphical-displas.html"><a href="graphical-displas.html#example"><i class="fa fa-check"></i><b>2.3</b> Example</a></li>
<li class="chapter" data-level="2.4" data-path="graphical-displas.html"><a href="graphical-displas.html#relative-frequency-distribution"><i class="fa fa-check"></i><b>2.4</b> Relative Frequency Distribution</a></li>
<li class="chapter" data-level="2.5" data-path="graphical-displas.html"><a href="graphical-displas.html#cumulative-frequency-distribution"><i class="fa fa-check"></i><b>2.5</b> Cumulative Frequency Distribution</a></li>
<li class="chapter" data-level="2.6" data-path="graphical-displas.html"><a href="graphical-displas.html#cumulative-relative-frequence"><i class="fa fa-check"></i><b>2.6</b> Cumulative Relative Frequence</a></li>
<li class="chapter" data-level="2.7" data-path="graphical-displas.html"><a href="graphical-displas.html#using-frequency-distributions-to-understand-data"><i class="fa fa-check"></i><b>2.7</b> Using Frequency Distributions to Understand Data</a></li>
<li class="chapter" data-level="2.8" data-path="graphical-displas.html"><a href="graphical-displas.html#gaps"><i class="fa fa-check"></i><b>2.8</b> Gaps</a></li>
<li class="chapter" data-level="2.9" data-path="graphical-displas.html"><a href="graphical-displas.html#what-do-gaps-tell-us"><i class="fa fa-check"></i><b>2.9</b> What Do Gaps Tell Us?</a></li>
<li class="chapter" data-level="2.10" data-path="graphical-displas.html"><a href="graphical-displas.html#histogram"><i class="fa fa-check"></i><b>2.10</b> Histogram</a></li>
<li class="chapter" data-level="2.11" data-path="graphical-displas.html"><a href="graphical-displas.html#important-uses-of-a-histogram"><i class="fa fa-check"></i><b>2.11</b> Important Uses of a Histogram</a></li>
<li class="chapter" data-level="2.12" data-path="graphical-displas.html"><a href="graphical-displas.html#example-of-a-histogram"><i class="fa fa-check"></i><b>2.12</b> Example of A Histogram</a></li>
<li class="chapter" data-level="2.13" data-path="graphical-displas.html"><a href="graphical-displas.html#interpreting-histograms"><i class="fa fa-check"></i><b>2.13</b> Interpreting Histograms</a></li>
<li class="chapter" data-level="2.14" data-path="graphical-displas.html"><a href="graphical-displas.html#common-distribution-shapes"><i class="fa fa-check"></i><b>2.14</b> Common Distribution Shapes</a></li>
<li class="chapter" data-level="2.15" data-path="graphical-displas.html"><a href="graphical-displas.html#assessing-normality-with-normal-quantile-plots-q-q-plots"><i class="fa fa-check"></i><b>2.15</b> Assessing Normality with Normal Quantile Plots (Q-Q plots)</a></li>
<li class="chapter" data-level="2.16" data-path="graphical-displas.html"><a href="graphical-displas.html#examples-of-q-q-plots"><i class="fa fa-check"></i><b>2.16</b> Examples of Q-Q plots</a></li>
<li class="chapter" data-level="2.17" data-path="graphical-displas.html"><a href="graphical-displas.html#dotplots"><i class="fa fa-check"></i><b>2.17</b> Dotplots</a></li>
<li class="chapter" data-level="2.18" data-path="graphical-displas.html"><a href="graphical-displas.html#stemplots-you-need-to-assign-a-key-to-read-a-stem-plot"><i class="fa fa-check"></i><b>2.18</b> Stemplots (You need to assign a key to read a stem plot)</a></li>
<li class="chapter" data-level="2.19" data-path="graphical-displas.html"><a href="graphical-displas.html#bar-graph"><i class="fa fa-check"></i><b>2.19</b> Bar Graph</a></li>
<li class="chapter" data-level="2.20" data-path="graphical-displas.html"><a href="graphical-displas.html#pareto-chart"><i class="fa fa-check"></i><b>2.20</b> Pareto Chart</a></li>
<li class="chapter" data-level="2.21" data-path="graphical-displas.html"><a href="graphical-displas.html#pie-charts"><i class="fa fa-check"></i><b>2.21</b> Pie Charts</a></li>
<li class="chapter" data-level="2.22" data-path="graphical-displas.html"><a href="graphical-displas.html#frequency-polygon"><i class="fa fa-check"></i><b>2.22</b> Frequency Polygon</a></li>
<li class="chapter" data-level="2.23" data-path="graphical-displas.html"><a href="graphical-displas.html#graphs-that-deceive"><i class="fa fa-check"></i><b>2.23</b> Graphs That Deceive</a></li>
<li class="chapter" data-level="2.24" data-path="graphical-displas.html"><a href="graphical-displas.html#pictographs"><i class="fa fa-check"></i><b>2.24</b> Pictographs</a></li>
<li class="chapter" data-level="2.25" data-path="graphical-displas.html"><a href="graphical-displas.html#scatterplot-two-numerical-variables"><i class="fa fa-check"></i><b>2.25</b> Scatterplot (Two Numerical Variables)</a></li>
<li class="chapter" data-level="2.26" data-path="graphical-displas.html"><a href="graphical-displas.html#nba"><i class="fa fa-check"></i><b>2.26</b> NBA</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>3</b> Descriptive Statistics</a><ul>
<li class="chapter" data-level="3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mean-or-arithmetic-mean"><i class="fa fa-check"></i><b>3.1</b> Mean (or Arithmetic Mean)</a></li>
<li class="chapter" data-level="3.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#notations"><i class="fa fa-check"></i><b>3.2</b> Notations</a></li>
<li class="chapter" data-level="3.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mean-example"><i class="fa fa-check"></i><b>3.3</b> Mean-Example</a></li>
<li class="chapter" data-level="3.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#median"><i class="fa fa-check"></i><b>3.4</b> Median</a></li>
<li class="chapter" data-level="3.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#median-example"><i class="fa fa-check"></i><b>3.5</b> Median-Example</a></li>
<li class="chapter" data-level="3.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#which-one-do-you-use-mean-or-median"><i class="fa fa-check"></i><b>3.6</b> Which one do you use? Mean or Median?</a></li>
<li class="chapter" data-level="3.7" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#which-one-do-you-use-mean-or-median-1"><i class="fa fa-check"></i><b>3.7</b> Which one do you use? Mean or Median?</a></li>
<li class="chapter" data-level="3.8" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mode"><i class="fa fa-check"></i><b>3.8</b> Mode</a></li>
<li class="chapter" data-level="3.9" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mode-example"><i class="fa fa-check"></i><b>3.9</b> Mode-Example</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="midrange.html"><a href="midrange.html"><i class="fa fa-check"></i><b>4</b> Midrange</a><ul>
<li class="chapter" data-level="4.1" data-path="midrange.html"><a href="midrange.html#round-off-rules-for-measures-of-center"><i class="fa fa-check"></i><b>4.1</b> Round-Off Rules for Measures of Center</a></li>
<li class="chapter" data-level="4.2" data-path="midrange.html"><a href="midrange.html#calculating-a-weighted-mean"><i class="fa fa-check"></i><b>4.2</b> Calculating a Weighted Mean</a></li>
<li class="chapter" data-level="4.3" data-path="midrange.html"><a href="midrange.html#more-examples-about-finding-the-means"><i class="fa fa-check"></i><b>4.3</b> More Examples About Finding The Means</a></li>
<li class="chapter" data-level="4.4" data-path="midrange.html"><a href="midrange.html#measures-of-variation"><i class="fa fa-check"></i><b>4.4</b> Measures of Variation</a></li>
<li class="chapter" data-level="4.5" data-path="midrange.html"><a href="midrange.html#round-off-rule-for-measures-of-variation"><i class="fa fa-check"></i><b>4.5</b> Round-off Rule for Measures of Variation</a></li>
<li class="chapter" data-level="4.6" data-path="midrange.html"><a href="midrange.html#range"><i class="fa fa-check"></i><b>4.6</b> Range</a></li>
<li class="chapter" data-level="4.7" data-path="midrange.html"><a href="midrange.html#standard-deviation"><i class="fa fa-check"></i><b>4.7</b> Standard Deviation</a></li>
<li class="chapter" data-level="4.8" data-path="midrange.html"><a href="midrange.html#formula"><i class="fa fa-check"></i><b>4.8</b> Formula</a></li>
<li class="chapter" data-level="4.9" data-path="midrange.html"><a href="midrange.html#interpretation-of-standard-deviation"><i class="fa fa-check"></i><b>4.9</b> Interpretation of Standard Deviation</a></li>
<li class="chapter" data-level="4.10" data-path="midrange.html"><a href="midrange.html#range-rule-of-thumb-for-understanding-standard-deviation"><i class="fa fa-check"></i><b>4.10</b> Range Rule of Thumb for Understanding Standard Deviation</a></li>
<li class="chapter" data-level="4.11" data-path="midrange.html"><a href="midrange.html#range-rule-of-thumb-for-estimating-a-value-of-the-standard-deviation-s"><i class="fa fa-check"></i><b>4.11</b> Range Rule of Thumb for Estimating a Value of the Standard Deviation s</a></li>
<li class="chapter" data-level="4.12" data-path="midrange.html"><a href="midrange.html#variance-of-a-sample-and-a-population"><i class="fa fa-check"></i><b>4.12</b> Variance of a Sample and a Population</a></li>
<li class="chapter" data-level="4.13" data-path="midrange.html"><a href="midrange.html#notations-1"><i class="fa fa-check"></i><b>4.13</b> Notations</a></li>
<li class="chapter" data-level="4.14" data-path="midrange.html"><a href="midrange.html#the-empirical-rule"><i class="fa fa-check"></i><b>4.14</b> The Empirical Rule</a></li>
<li class="chapter" data-level="4.15" data-path="midrange.html"><a href="midrange.html#chebyshevs-theorem"><i class="fa fa-check"></i><b>4.15</b> Chebyshev’s Theorem</a></li>
<li class="chapter" data-level="4.16" data-path="midrange.html"><a href="midrange.html#extra-example"><i class="fa fa-check"></i><b>4.16</b> Extra Example</a></li>
<li class="chapter" data-level="4.17" data-path="midrange.html"><a href="midrange.html#measures-of-relative-standing-and-boxplots"><i class="fa fa-check"></i><b>4.17</b> Measures of Relative Standing and Boxplots</a></li>
<li class="chapter" data-level="4.18" data-path="midrange.html"><a href="midrange.html#z-scores"><i class="fa fa-check"></i><b>4.18</b> z Scores</a></li>
<li class="chapter" data-level="4.19" data-path="midrange.html"><a href="midrange.html#important-properties-of-z-scores"><i class="fa fa-check"></i><b>4.19</b> Important Properties of z Scores</a></li>
<li class="chapter" data-level="4.20" data-path="midrange.html"><a href="midrange.html#examples"><i class="fa fa-check"></i><b>4.20</b> Examples</a></li>
<li class="chapter" data-level="4.21" data-path="midrange.html"><a href="midrange.html#percentiles"><i class="fa fa-check"></i><b>4.21</b> Percentiles</a></li>
<li class="chapter" data-level="4.22" data-path="midrange.html"><a href="midrange.html#interpretation-of-percentiles"><i class="fa fa-check"></i><b>4.22</b> Interpretation of Percentiles</a></li>
<li class="chapter" data-level="4.23" data-path="midrange.html"><a href="midrange.html#example-from-a-dataset"><i class="fa fa-check"></i><b>4.23</b> Example from a dataset</a></li>
<li class="chapter" data-level="4.24" data-path="midrange.html"><a href="midrange.html#notations-2"><i class="fa fa-check"></i><b>4.24</b> Notations</a></li>
<li class="chapter" data-level="4.25" data-path="midrange.html"><a href="midrange.html#converting-a-percentile-to-a-data-value"><i class="fa fa-check"></i><b>4.25</b> Converting a Percentile to a Data Value</a></li>
<li class="chapter" data-level="4.26" data-path="midrange.html"><a href="midrange.html#example-5"><i class="fa fa-check"></i><b>4.26</b> Example</a></li>
<li class="chapter" data-level="4.27" data-path="midrange.html"><a href="midrange.html#quartiles"><i class="fa fa-check"></i><b>4.27</b> Quartiles</a></li>
<li class="chapter" data-level="4.28" data-path="midrange.html"><a href="midrange.html#statistics-defined-using-quartiles-and-percentiles"><i class="fa fa-check"></i><b>4.28</b> Statistics defined using quartiles and percentiles</a></li>
<li class="chapter" data-level="4.29" data-path="midrange.html"><a href="midrange.html#number-summary"><i class="fa fa-check"></i><b>4.29</b> 5-Number Summary</a></li>
<li class="chapter" data-level="4.30" data-path="midrange.html"><a href="midrange.html#example-finding-a-5-number-summary"><i class="fa fa-check"></i><b>4.30</b> Example: Finding a 5-Number Summary</a></li>
<li class="chapter" data-level="4.31" data-path="midrange.html"><a href="midrange.html#boxplot-or-box-and-whisker-diagram"><i class="fa fa-check"></i><b>4.31</b> Boxplot (or Box-and-Whisker Diagram)</a></li>
<li class="chapter" data-level="4.32" data-path="midrange.html"><a href="midrange.html#procedure-for-constructing-a-boxplot"><i class="fa fa-check"></i><b>4.32</b> Procedure for Constructing a Boxplot</a></li>
<li class="chapter" data-level="4.33" data-path="midrange.html"><a href="midrange.html#skewness"><i class="fa fa-check"></i><b>4.33</b> Skewness</a></li>
<li class="chapter" data-level="4.34" data-path="midrange.html"><a href="midrange.html#identifying-outliers-for-modified-boxplots"><i class="fa fa-check"></i><b>4.34</b> Identifying Outliers for Modified Boxplots</a></li>
<li class="chapter" data-level="4.35" data-path="midrange.html"><a href="midrange.html#modified-boxplot"><i class="fa fa-check"></i><b>4.35</b> Modified Boxplot</a></li>
<li class="chapter" data-level="4.36" data-path="midrange.html"><a href="midrange.html#example-6"><i class="fa fa-check"></i><b>4.36</b> Example</a></li>
<li class="chapter" data-level="4.37" data-path="midrange.html"><a href="midrange.html#comparative-boxplots"><i class="fa fa-check"></i><b>4.37</b> Comparative Boxplots</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>5</b> Methods</a></li>
<li class="chapter" data-level="6" data-path="applications.html"><a href="applications.html"><i class="fa fa-check"></i><b>6</b> Applications</a><ul>
<li class="chapter" data-level="6.1" data-path="applications.html"><a href="applications.html#example-one"><i class="fa fa-check"></i><b>6.1</b> Example one</a></li>
<li class="chapter" data-level="6.2" data-path="applications.html"><a href="applications.html#example-two"><i class="fa fa-check"></i><b>6.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>7</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Math 115: Elementary Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="midrange" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Midrange</h1>
<ul>
<li>Midrange is the value midway between the maximum and minimum values in the original data set</li>
<li><span class="math inline">\(Midrange=\frac{Maximum \enspace Value +Minimum \enspace Value}{2}\)</span></li>
<li>Because the midrange uses only the maximum and minimum values, it is very sensitive to those extremes so the midrange is not resistant.</li>
</ul>
<div id="round-off-rules-for-measures-of-center" class="section level2">
<h2><span class="header-section-number">4.1</span> Round-Off Rules for Measures of Center</h2>
<ul>
<li>For the mean, median, and midrange, carry one more decimal place than is present in the original set of values.</li>
<li>For the mode, leave the value as is without rounding (because values of the mode are the same as some of the original data values).</li>
</ul>
</div>
<div id="calculating-a-weighted-mean" class="section level2">
<h2><span class="header-section-number">4.2</span> Calculating a Weighted Mean</h2>
<ul>
<li>When data values are assigned different weights, <span class="math inline">\(w\)</span>, we can compute a weighted mean.
<span class="math display">\[\bar{x}=\frac{\sum{(w\cdot x)}}{\sum{w}}\]</span></li>
<li>In her first semester of college, a student of the author took five courses.
Her final grades along with the number of credits for each course were A (3 credits), A (4 credits), B (3 credits), C (3 credits), and F (1 credit).
The grading system assigns quality points to letter grades as follows:
A = 4; B = 3; C = 2; D = 1; F = 0.</li>
</ul>
</div>
<div id="more-examples-about-finding-the-means" class="section level2">
<h2><span class="header-section-number">4.3</span> More Examples About Finding The Means</h2>
<ul>
<li>Angelique made scores of 85, 56, and 91 on her first three statistic tests. What does she need to make on her next test to have an 80 test average?</li>
<li>Mr. Plum’s math class of 25 students had an average of 85 on a test. Miss Scarlet’s class of 22 students had an average of 87 on the same test. What is the average of the two classes combined?</li>
<li><font color="red"> Consider</font> the time that it takes the faculty of AVC to drive to school. The mean and median times are calculated. Of the times, 40 minutes and 25 minutes, which is the mean and which is the median? Why?</li>
</ul>
</div>
<div id="measures-of-variation" class="section level2">
<h2><span class="header-section-number">4.4</span> Measures of Variation</h2>
<p>Variation is the single most important topic in statistics, so this is the single most important section in this book. This section presents three important measures of variation: range, standard deviation, and variance.
These statistics are numbers, but our focus is not just computing those numbers but developing the ability to interpret and understand them.</p>
</div>
<div id="round-off-rule-for-measures-of-variation" class="section level2">
<h2><span class="header-section-number">4.5</span> Round-off Rule for Measures of Variation</h2>
<p>When rounding the value of a measure of variation, carry one more decimal place than is present in the original set of data.</p>
</div>
<div id="range" class="section level2">
<h2><span class="header-section-number">4.6</span> Range</h2>
<ul>
<li>The range of a set of data values is the difference between the maximum data value and the minimum data value.</li>
<li>Range = (maximum value) - (minimum value)</li>
<li>It is very sensitive to extreme values; therefore, it is not as useful as other measures of variation.</li>
<li>Because the range uses only the maximum and minimum values, it does not take every value into account and therefore does not truly reflect the variation among all of the data values.</li>
<li>Find the range of these Verizon data speeds (Mbps): 38.5, 55.6, 22.4, 14.1, 23.1.</li>
</ul>
</div>
<div id="standard-deviation" class="section level2">
<h2><span class="header-section-number">4.7</span> Standard Deviation</h2>
<ul>
<li>The <strong>standard deviation</strong> of a set of sample values, denoted by s, is a measure of how much data values deviate away from the mean.</li>
<li><strong>s</strong>: sample standard deviation</li>
<li><span class="math inline">\(\sigma\)</span>: population standard deviation</li>
</ul>
</div>
<div id="formula" class="section level2">
<h2><span class="header-section-number">4.8</span> Formula</h2>
<ul>
<li><p>Sample standard deviation:
<span class="math display">\[s=\sqrt{\frac{\sum (x_i-\bar{x})^2}{n-1}}\]</span>
or
<span class="math display">\[s=\sqrt{\frac{n\sum (x_i^2)-\sum(x_i)^2}{n(n-1)}}\]</span></p></li>
<li><p>Population standard deviation
<span class="math display">\[\sigma=\sqrt{\frac{\sum (x_i-\mu)^2}{N}}\]</span></p></li>
</ul>
</div>
<div id="interpretation-of-standard-deviation" class="section level2">
<h2><span class="header-section-number">4.9</span> Interpretation of Standard Deviation</h2>
<ul>
<li>The standard deviation is a measure of variation of all values from the mean; or a measure of how much data values deviate away from the mean.</li>
<li>The value of the standard deviation s is never negative. It is zero only when all of the data values are exactly the same.</li>
<li>The value of the standard deviation s can increase dramatically with the inclusion of one or more outliers (data values far away from all others).</li>
<li>The units of the standard deviation s are the same as the units of the original data values.</li>
<li>Larger values of <span class="math inline">\(s\)</span> indicate greater amounts of variation.</li>
<li>The sample standard deviation <span class="math inline">\(s\)</span> is a <strong>biased estimator</strong> of the population standard deviation <span class="math inline">\(\sigma\)</span>, which means that values of the sample standard deviation <span class="math inline">\(s\)</span> do not center around the value of <span class="math inline">\(\sigma\)</span>.</li>
<li>Use sample standard deviation formula to find the standard deviation of these Verizon data speed times (in Mbps): 38.5, 55.6, 22.4, 14.1, 23.1.</li>
</ul>
</div>
<div id="range-rule-of-thumb-for-understanding-standard-deviation" class="section level2">
<h2><span class="header-section-number">4.10</span> Range Rule of Thumb for Understanding Standard Deviation</h2>
<ul>
<li>The range rule of thumb is a crude but simple tool for understanding and interpreting standard deviation. The vast majority (such as 95%) of sample values lie within 2 standard deviations of the mean.</li>
<li>Significantly low values are <span class="math inline">\(\mu-2\sigma\)</span> or lower. (Minimum “usual” value = (mean) - 2 <span class="math inline">\(\times\)</span> (standard deviation))</li>
<li>Significantly high values are <span class="math inline">\(\mu+2\sigma\)</span> or higher. (Maximum “usual” value = (mean) + 2 <span class="math inline">\(\times\)</span> (standard deviation))</li>
<li>Values not significant are between <span class="math inline">\(\mu-2\sigma\)</span> and <span class="math inline">\(\mu+2\sigma\)</span>.</li>
<li><img src="pic9.png" /></li>
<li>Using the 40 chocolate chip counts for the Chips Ahoy cookies, the mean is 24.0 chips and the standard deviation is 2.6 chips.
<ul>
<li>Use the range rule of thumb to find the minimum and maximum “usual” numbers of chips.\</li>
<li>Would a cookie with 30 chocolate chips be “unusual”?</li>
</ul></li>
</ul>
</div>
<div id="range-rule-of-thumb-for-estimating-a-value-of-the-standard-deviation-s" class="section level2">
<h2><span class="header-section-number">4.11</span> Range Rule of Thumb for Estimating a Value of the Standard Deviation s</h2>
<ul>
<li>To roughly estimate the standard deviation from a collection of known sample data use
<span class="math display">\[s\approx \frac{Range}{4}\]</span>
where range = (maximum value) - (minimum value)</li>
</ul>
</div>
<div id="variance-of-a-sample-and-a-population" class="section level2">
<h2><span class="header-section-number">4.12</span> Variance of a Sample and a Population</h2>
<ul>
<li>The <strong>variance</strong> of a set of values is a measure of variation equal to the square of the standard deviation.
<ul>
<li>Sample variance: <span class="math inline">\(s^2\)</span> - Square of the sample standard deviation <span class="math inline">\(s\)</span></li>
<li>Population variance: <span class="math inline">\(\sigma^2\)</span> - Square of the population standard deviation <span class="math inline">\(\sigma\)</span></li>
<li>The units of the variance are the squares of the units of the original data values.</li>
<li>The value of the variance can increase dramatically with the inclusion of outliers. (The variance is not resistant.)</li>
<li>The value of the variance is never negative. It is zero only when all of the data values are the same number.</li>
<li>The sample variance <span class="math inline">\(s^2\)</span> is an unbiased estimator of the population variance <span class="math inline">\(\sigma^2\)</span>.</li>
</ul></li>
</ul>
</div>
<div id="notations-1" class="section level2">
<h2><span class="header-section-number">4.13</span> Notations</h2>
<ul>
<li><span class="math inline">\(s\)</span>: samle standard deviation</li>
<li><span class="math inline">\(n\)</span>: sample size</li>
<li><span class="math inline">\(s^2\)</span>: sample variance</li>
<li><span class="math inline">\(\sigma\)</span>: population standard deviation</li>
<li><span class="math inline">\(N\)</span>: population size</li>
<li><span class="math inline">\(\sigma^2\)</span>: population variance</li>
</ul>
</div>
<div id="the-empirical-rule" class="section level2">
<h2><span class="header-section-number">4.14</span> The Empirical Rule</h2>
<ul>
<li><img src="pic10.png" /></li>
<li>IQ scores have a bell-shaped distribution with a mean of 100 and a standard deviation of 15. What percentage of IQ scores are between 70 and 130?</li>
</ul>
</div>
<div id="chebyshevs-theorem" class="section level2">
<h2><span class="header-section-number">4.15</span> Chebyshev’s Theorem</h2>
<p><img src="pic11.jpg" /></p>
</div>
<div id="extra-example" class="section level2">
<h2><span class="header-section-number">4.16</span> Extra Example</h2>
<ul>
<li>A list has 10 numbers. Each number is a 1, 2, or 3. The average is 2 and the SD is 0. What is the list?</li>
</ul>
</div>
<div id="measures-of-relative-standing-and-boxplots" class="section level2">
<h2><span class="header-section-number">4.17</span> Measures of Relative Standing and Boxplots</h2>
<ul>
<li>This section introduces measures of relative standing, which are numbers showing the location of data values relative to the other values within a data set.</li>
<li>They can be used to compare values from different data sets, or to compare values within the same data set.<br />
</li>
<li>The most important concept is the z score.</li>
<li>We will also discuss percentiles and quartiles, as well as a new statistical graph called the boxplot.</li>
</ul>
</div>
<div id="z-scores" class="section level2">
<h2><span class="header-section-number">4.18</span> z Scores</h2>
<ul>
<li>z-score (or standardized value) is the number of standard deviations that a given value x is above or below the mean.</li>
<li>z-score of a sample data value: <span class="math inline">\(z=\frac{x-\bar{x}}{s}\)</span></li>
<li>z-score of a population data value: <span class="math inline">\(z=\frac{x-\mu}{\sigma}\)</span></li>
<li>Round z scores to two decimal places</li>
</ul>
</div>
<div id="important-properties-of-z-scores" class="section level2">
<h2><span class="header-section-number">4.19</span> Important Properties of z Scores</h2>
<ul>
<li>A z-score is the number of standard deviations that a given value x is above or below the mean.</li>
<li>z-scores are expressed as numbers with no units of measurement.</li>
<li>A data value is significantly low if its z-score is less than or equal to -2 or the value is significantly high if its z-score is greater than or equal to +2.</li>
<li>If an individual data value is less than the mean, its corresponding z score is a negative number.</li>
<li><img src="pic12.png" /></li>
</ul>
</div>
<div id="examples" class="section level2">
<h2><span class="header-section-number">4.20</span> Examples</h2>
<ul>
<li>Suppose the mean and standard deviation of a distribution are <span class="math inline">\(\mu=50\)</span> and <span class="math inline">\(s = 5\)</span>
<ul>
<li>If the x-value is 55, what is the z-score?</li>
<li>If the x-value is 45, what is the z-score?</li>
<li>If the x-value is 60, what is the z-score?</li>
<li>So what does the z-score tell you?</li>
<li>The author of the text measured his pulse rate to be 48 beats per minute. Is that pulse rate unusual if the mean adult male pulse rate is 67.3 beats per minute with a standard deviation of 10.3?</li>
<li>Sally is taking two different math achievement tests with different means and standard deviations. The mean score on test A was 56 with a standard deviation of 3.5, while the mean score on test B was 65 with a standard deviation of 2.8. Sally scored a 62 on test A and a 69 on test B. On which test did Sally score the best? Why?</li>
</ul></li>
</ul>
</div>
<div id="percentiles" class="section level2">
<h2><span class="header-section-number">4.21</span> Percentiles</h2>
<ul>
<li><strong>Percentiles</strong> are measures of location, denoted <span class="math inline">\(P_1\)</span>, <span class="math inline">\(P_2\)</span>, . . . , <span class="math inline">\(P_99\)</span>, which divide a set of data into 100 groups with about 1% of the values in each group.</li>
<li>The process of finding the percentile that corresponds to a particular data value x is given by the following (round the result to the nearest whole number)
<span class="math display">\[\textrm{Percentile of a data value x}=\frac{\textrm{number of values less than x}}{\textrm{total number of values}}\times 100\]</span></li>
<li>The airport Verizon cell phone data speeds listed below are arranged in increasing order. Find the percentile for the data speed of 11.8 Mbps.
<img src="pic13.png" /></li>
</ul>
</div>
<div id="interpretation-of-percentiles" class="section level2">
<h2><span class="header-section-number">4.22</span> Interpretation of Percentiles</h2>
<ul>
<li>From the previous example: A data speed of 11.8 Mbps is in the 40th percentile. This can be interpreted loosely as this:
A data speed of 11.8 Mbps separates the lowest 40% of values from the highest 60% of values. We have <span class="math inline">\(P_{40} = 11.8\)</span> Mbps.</li>
<li>Better interpretation: 40% of the data values are less than 11.8 Mbps or 60% of the data values are greater than 11.8 Mbps</li>
<li>What is the percentile for the median? How would you interpret the median better?</li>
</ul>
</div>
<div id="example-from-a-dataset" class="section level2">
<h2><span class="header-section-number">4.23</span> Example from a dataset</h2>
<pre><code>##   height ideal_ht sleep fastest
## 1     76       78   9.5     119
## 2     74       76   7.0     110
## 3     64       NA   9.0      85
## 4     62       65   7.0     100
## 5     72       72   8.0      95</code></pre>
<pre><code>## 20% 50% 80% 90% 
##  90 102 120 130</code></pre>
<ul>
<li>Interpet the meanings of the above perentiles
<ul>
<li>About 20% of the students drove slower than 90 mph</li>
<li>About 50% of the students drove slower than 102 mph (median!)</li>
<li>About 80% of the students drove slower than 120 mph</li>
<li>About 90% of the students drove slower than 130 mph</li>
</ul></li>
</ul>
</div>
<div id="notations-2" class="section level2">
<h2><span class="header-section-number">4.24</span> Notations</h2>
<ul>
<li>n total number of values in the data set</li>
<li>k percentile being used (Example: For the 25th percentile, k = 25.)</li>
<li>L locator that gives the position of a value (Example: For the 12th value in the sorted list, L = 12.)</li>
<li><span class="math inline">\(P_k\)</span> kth percentile (Example: <span class="math inline">\(P_{25}\)</span> is the 25th percentile.)</li>
</ul>
</div>
<div id="converting-a-percentile-to-a-data-value" class="section level2">
<h2><span class="header-section-number">4.25</span> Converting a Percentile to a Data Value</h2>
<ol style="list-style-type: decimal">
<li>Find L, where <span class="math inline">\(L=\frac{k}{100}\times n\)</span></li>
<li>If L is not a whole number, round up to the next whole number and find the data value in that position. If L is a whole number, average the data values in position L and L+1. (Notes: You need to put the numbers in order from small to large first.)</li>
</ol>
</div>
<div id="example-5" class="section level2">
<h2><span class="header-section-number">4.26</span> Example</h2>
<p>Refer to the sorted data speeds below. Find the 40th and 60th percentile, denoted by <span class="math inline">\(P_{40}\)</span> and <span class="math inline">\(P_{60}\)</span>, respectively.</p>
<p><img src="pic13.png" /></p>
</div>
<div id="quartiles" class="section level2">
<h2><span class="header-section-number">4.27</span> Quartiles</h2>
<ul>
<li>Quartiles are measures of location, denoted <span class="math inline">\(Q_1\)</span>, <span class="math inline">\(Q_2\)</span>, and <span class="math inline">\(Q_3\)</span>, which divide a set of data into four groups with about 25% of the values in each group</li>
<li><span class="math inline">\(Q_1\)</span> (First quartile): Same value as <span class="math inline">\(P_{25}\)</span>. It separates the bottom 25% of the sorted values from the top 75%.</li>
<li><span class="math inline">\(Q_2\)</span> (Second quartile): Same as <span class="math inline">\(P_{50}\)</span> and same as the <strong>median</strong>. It separates the bottom 50% of the sorted values from the top 50%.</li>
<li><span class="math inline">\(Q_3\)</span> (Third quartile): Same as <span class="math inline">\(P_{75}\)</span>. It separates the bottom 75% of the sorted values from the top 25%.</li>
<li>Different technologies often yield different results.</li>
<li><img src="pic14.png" /></li>
</ul>
</div>
<div id="statistics-defined-using-quartiles-and-percentiles" class="section level2">
<h2><span class="header-section-number">4.28</span> Statistics defined using quartiles and percentiles</h2>
<p>Just focus on the Interquartile Range (IQR)
<img src="pic15.jpg" /></p>
</div>
<div id="number-summary" class="section level2">
<h2><span class="header-section-number">4.29</span> 5-Number Summary</h2>
<ul>
<li>For a set of data, the 5-number summary consists of these five values:
<ul>
<li>Minimum</li>
<li><span class="math inline">\(Q_1\)</span></li>
<li><span class="math inline">\(Q_2\)</span> or median</li>
<li><span class="math inline">\(Q_3\)</span></li>
<li>Maximum</li>
</ul></li>
</ul>
</div>
<div id="example-finding-a-5-number-summary" class="section level2">
<h2><span class="header-section-number">4.30</span> Example: Finding a 5-Number Summary</h2>
<p>Use the Verizon airport data speeds to find the 5-number summary.</p>
<p><img src="pic13.png" /></p>
</div>
<div id="boxplot-or-box-and-whisker-diagram" class="section level2">
<h2><span class="header-section-number">4.31</span> Boxplot (or Box-and-Whisker Diagram)</h2>
<ul>
<li>A boxplot (or box-and-whisker diagram) is a graph of a data set that consists of a line extending from the minimum value to the maximum value, and a box with lines drawn at the first quartile <span class="math inline">\(Q_1\)</span>, the median, and the third quartile <span class="math inline">\(Q_3\)</span>.</li>
</ul>
</div>
<div id="procedure-for-constructing-a-boxplot" class="section level2">
<h2><span class="header-section-number">4.32</span> Procedure for Constructing a Boxplot</h2>
<ol style="list-style-type: decimal">
<li>Find the 5-number summary (minimum value, <span class="math inline">\(Q_1\)</span>, <span class="math inline">\(Q_2\)</span>, <span class="math inline">\(Q_3\)</span>, maximum value).</li>
<li>Construct a line segment extending from the minimum data value to the maximum data value.</li>
<li>Construct a box (rectangle) extending from Q1 to Q3, and draw a line in the box at the value of Q2 (median).</li>
</ol>
<ul>
<li>Use the Verizon airport data speeds to construct a boxplot.</li>
<li><img src="pic15.png" /></li>
</ul>
</div>
<div id="skewness" class="section level2">
<h2><span class="header-section-number">4.33</span> Skewness</h2>
<ul>
<li>A boxplot can often be used to identify skewness. A distribution of data is skewed if it is not symmetric and extends more to one side than to the other.</li>
<li><img src="pic16.png" /></li>
</ul>
</div>
<div id="identifying-outliers-for-modified-boxplots" class="section level2">
<h2><span class="header-section-number">4.34</span> Identifying Outliers for Modified Boxplots</h2>
<ol style="list-style-type: decimal">
<li>Find the quartiles <span class="math inline">\(Q_1\)</span>, <span class="math inline">\(Q_2\)</span>, and <span class="math inline">\(Q_3\)</span>.</li>
<li>Find the interquartile range (IQR), where <span class="math inline">\(\textrm{IQR} = Q_3- Q_1\)</span>.</li>
<li>Evaluate <span class="math inline">\(1.5\times \textrm{IQR}\)</span>.</li>
<li>In a modified boxplot, a data value is an outlier if it is above <span class="math inline">\(Q_3\)</span>, by an amount greater than <span class="math inline">\(1.5\times \textrm{IQR}\)</span> or below <span class="math inline">\(Q_1\)</span>, by an amount greater than <span class="math inline">\(1.5\times \textrm{IQR}\)</span>.</li>
</ol>
</div>
<div id="modified-boxplot" class="section level2">
<h2><span class="header-section-number">4.35</span> Modified Boxplot</h2>
<p><img src="pic17.png" /></p>
</div>
<div id="example-6" class="section level2">
<h2><span class="header-section-number">4.36</span> Example</h2>
<pre><code>##  min  Q1 median Q3 max mean sd  n missing
##  0.8 8.4     14 21  78   18 16 50       0</code></pre>
<p><img src="Book_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre><code>## $stats
## [1]  0.8  7.9 13.9 21.5 38.5
## 
## $n
## [1] 50
## 
## $conf
## [1] 11 17
## 
## $out
## [1] 43 56 71 78</code></pre>
</div>
<div id="comparative-boxplots" class="section level2">
<h2><span class="header-section-number">4.37</span> Comparative Boxplots</h2>
<p><img src="Book_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="descriptive-statistics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="methods.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["Book.pdf", "Book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
